In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
import os
from sklearn.tree import DecisionTreeClassifier,export_graphviz
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from IPython.display import Image

In [3]:
df = pd.read_csv("Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
X = df.iloc[:,[1,2,3,4]].values
y = df.iloc[:,[5]].values

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X, y, random_state = 0)
import pydotplus

In [21]:
a = DecisionTreeClassifier(criterion="entropy",random_state=100,max_depth=4,min_samples_leaf=5)
a.fit(X_train,y_train)
y_pred = a.predict(X_test)

In [25]:
print("Confusion Matix : \n", confusion_matrix(y_test,y_pred))
print("\n")
print("Accuracy :",accuracy_score(y_test,y_pred) * 100)
print("\n")
print("Report :", classification_report(y_test,y_pred))

Confusion Matix : 
 [[13  0  0]
 [ 0 15  1]
 [ 0  3  6]]


Accuracy : 89.47368421052632


Report :                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       0.83      0.94      0.88        16
 Iris-virginica       0.86      0.67      0.75         9

       accuracy                           0.89        38
      macro avg       0.90      0.87      0.88        38
   weighted avg       0.90      0.89      0.89        38



In [33]:
b = RandomForestClassifier(max_depth=None,n_estimators=100) 
b.fit(X_train,y_train)
y_pred = b.predict(X_test)
print("Confusion Matix : \n", confusion_matrix(y_test,y_pred))
print("\n")
print("Accuracy :",accuracy_score(y_test,y_pred) * 100)
print("\n")
print("Report :", classification_report(y_test,y_pred))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


Confusion Matix : 
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


Accuracy : 97.36842105263158


Report :                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.94      0.97        16
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        38
      macro avg       0.97      0.98      0.97        38
   weighted avg       0.98      0.97      0.97        38

